#pragma once

#include "../includes.h"

#ifndef SHIPS_MORSKOY_BOY_GAMEMASTER_GAMEMASTER_H_
#define SHIPS_MORSKOY_BOY_GAMEMASTER_GAMEMASTER_H_

class GameMaster {

};

#endif //SHIPS_MORSKOY_BOY_GAMEMASTER_GAMEMASTER_H_
